#!/bin/sh

# Load system X11 scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Start the policykit agent for GUI authentication
/usr/lib/lxqt-policykit/lxqt-policykit-agent &

# Launch i3 window manager
exec i3
